services:
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "5008:5008"
    networks:
      backend_network:
        ipv4_address: 172.29.1.3

  mongo:
    image: mongo:5
    container_name: mongo
    volumes:
      - /mnt/database/data/mongo-1:/data/db
    networks:
      backend_network:
        ipv4_address: 172.29.1.2
    restart: always

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.29.1.0/24"
